in prog

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -3,13 +3,27 @@
 # Run the following command in the root of your project to install this pre-push hook:
 # cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push
 
-# Check if we actually have commits to push
+# ---- Run single_header build ---- #
+
+MAKE_SINGLE_HEADER="cmake --build --preset=dev -t make_single_header && ./build/dev/tools/make_single_header ./include/libfork.hpp ./single_header/libfork.hpp"
+
+eval $MAKE_SINGLE_HEADER
+
+if [ $? -ne 0 ]; then
+    echo "$MAKE_SINGLE_HEADER failed!"
+    exit 1
+fi
+
+git add ./single_header/libfork.hpp 
+
+# ---- Check if we actually have commits to push ---- #
+
 commits=`git log @{u}..`
 if [ -z "$commits" ]; then
     exit 0
 fi
 
-# Check there are no untracked changes
+# ---- Check there are no untracked changes ---- #
 
 pattern=$(git config --get hooks.prepush.sourcepattern)
 if [ -z "$pattern" ]; then
@@ -28,6 +42,8 @@ if [ -n "$files" ]; then
     echo
     exit 1
 fi
+
+# ---- Run linter ---- #
     
 LINT="cmake --build --preset=dev -t spell-check format-check"
 
@@ -37,6 +53,8 @@ if [ $? -ne 0 ]; then
     echo "Lint: $LINT failed!"
     exit 1
 fi
+
+# ---- Run tests ---- #
 
 TEST="cmake --build --preset=dev && ctest --preset=dev"
 
