test fail 3

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -10,12 +10,25 @@ fi
 
 # Check there are no untracked changes
 
-git diff-index --quiet HEAD --
-
-if [ $? -ne 0 ]; then
-    echo "Untracked changes!"
-    exit 1
+pattern=$(git config --get hooks.prepush.sourcepattern)
+if [ -z "$pattern" ]; then
+    pattern="(?:(?:^|/)CMakeLists\.txt|\.h|\.cpp|\.cmake)$"
 fi
+    
+files=$(git status -u --porcelain --no-column | sed "s/^?? //" | grep -P "$pattern")
+if [ -z "$files" ]; then
+    exit 0
+fi
+    
+echo
+echo "ERROR: Preventing push with untracked source files:"
+echo
+echo "$files" | sed "s/^/    /"
+echo
+echo "Either include these files in your commits, add them to .gitignore"
+echo "or stash them with git stash -u."
+echo
+exit 1
 
 LINT="cmake --preset=dev && cmake --build --preset=dev -t spell-check format-check"
 
@@ -27,6 +40,8 @@ if [ $? -ne 0 ]; then
 fi
 
 TEST="cmake --build --preset=dev && ctest --preset=dev"
+
+
 
 eval $TEST
 
