test fail 6

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -16,20 +16,18 @@ if [ -z "$pattern" ]; then
 fi
     
 files=$(git status -u --porcelain --no-column | sed "s/^?? //" | grep -P "$pattern")
-if [ -z "$files" ]; then
-    exit 0
+if [ -n "$files" ]; then
+    echo
+    echo "ERROR: Preventing push with untracked source files:"
+    echo
+    echo "$files" | sed "s/^/    /"
+    echo
+    echo "Either include these files in your commits, add them to .gitignore"
+    echo "or stash them with git stash -u."
+    echo
+    exit 1
 fi
     
-echo
-echo "ERROR: Preventing push with untracked source files:"
-echo
-echo "$files" | sed "s/^/    /"
-echo
-echo "Either include these files in your commits, add them to .gitignore"
-echo "or stash them with git stash -u."
-echo
-
-
 LINT="cmake --preset=dev && cmake --build --preset=dev -t spell-check format-check"
 
 eval $LINT
